#######################################################################################
# EKS Auto Mode Custom Nodepool Conf SPOT 
###################################################################################

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-nodepool
spec:
  weight: 80 # Spot preferred more often
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
  template:
    metadata:
      labels:
        workload: nodejs-microservice
        capacity: spot
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: eks.amazonaws.com/instance-category
        operator: In
        values: ["c", "m", "r"]
      - key: eks.amazonaws.com/instance-generation
        operator: Gt
        values: ["5"]
      # - key: eks.amazonaws.com/instance-size
      #   operator: In
      #   values: ["2xlarge", "4xlarge", "8xlarge", "16xlarge", "32xlarge"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      terminationGracePeriod: 5m
