serviceAccount:
  create: true
  name: fluent-bit
  automountServiceAccountToken: false

rbac:
  create: true

image:
  repository: public.ecr.aws/aws-observability/aws-for-fluent-bit
  tag: stable
  pullPolicy: IfNotPresent

priorityClassName: system-cluster-critical

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podDisruptionBudget:
  maxUnavailable: 0

# tolerations:
#   - key: CriticalAddonsOnly
#     operator: Equal
#     value: "true"
#     effect: NoSchedule

logLevel: info
flush: 1
metricsPort: 2020

config:
  service: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        Off
        Parsers_File  /fluent-bit/etc/parsers.conf
        Parsers_File  /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        multiline.parser  docker, cri
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        storage.type      filesystem

    [INPUT]
        Name              systemd
        Tag               host.*
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail    On

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  # outputs: |
  #   [OUTPUT]
  #       Name                    loki
  #       Match                   *
  #       Host                    grafana.aavgo.com
  #       Port                    443
  #       TLS                     On
  #       TLS.Verify              Off
  #       HTTP_User               admin
  #       HTTP_Passwd             your_strong_password_here
  #       Line_Format             json
  #       Auto_Kubernetes_Labels  On
  #       Labels                  job=fluentbit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name']
  #       Log_Level               info

  outputs: |
    [OUTPUT]
        Name                    http
        Match                   *
        URI                     /api/default/default/_json
        Host                    monitoring.aavgo.com
        Port                    443
        tls                     On
        Format                  json
        Json_date_key           _timestamp
        Json_date_format        iso8601
        HTTP_User               admin@example.com
        HTTP_Passwd             2jCeEMWOurPgp8BD
        compress                gzip
        Retry_Limit             False
        Batch_Size              500

  customParsers: |
    [PARSER]
        Name        docker_no_time
        Format      json
        Time_Keep   Off
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L


#Command#


# - helm repo add fluent https://fluent.github.io/helm-charts
# - helm repo update


# helm install fluent-bit fluent/fluent-bit \
#   --namespace logging \
#   --create-namespace \
#   -f fluentbit-values.yaml

# helm upgrade fluent-bit fluent/fluent-bit \
#   --namespace logging \
#   -f fluentbit-values.yaml
