apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: all-services-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      environment: sandbox  # Use a common label all services share