# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: all-services-pdb
#   namespace: terotam
# spec:
#   minAvailable: 1
#   selector:
#     matchLabels:
#       environment: sandbox  # Use a common label all services share


# ========== PDBs for all services ==========
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cron-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cron
      environment: sandbox

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pm-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pm
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gm-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gm
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cm-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cm
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sca-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sca
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bulk-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bulk
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: assets-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: assets
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: invoice-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: invoice
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: store-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: store
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: puppeteer-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: puppeteer
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dashboard-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dashboard
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enquiry-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: enquiry
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: utility-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: utility
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: device-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: device
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: qr-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: qr
      environment: sandbox
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: main-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: main
      environment: sandbox


---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis
      environment: sandbox

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dozzle-pdb
  namespace: terotam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dozzle
      environment: sandbox
