apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-auto-optimized
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: terotam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-auto-optimized
  resources:
    requests:
      storage: 25Gi